name = "redirekt"
type = "webpack"
zone_id = "**redacted**"
account_id = "**redacted**"
routes = ["prateekpunetha.dev/*", "download.prateekpunetha.dev/*"]
workers_dot_dev = false
webpack_config = "webpack.config.js"
